version: "3"

services:
  nginx:
    image: nginx
    ports:
      - 8000:80
    volumes:
      - ./public:/app
      - ./server.conf:/etc/nginx/conf.d/default.conf
  php:
    image: php:7.4-fpm
    volumes:
      - ./public:/app
